image:
  file: .gitpod.dockerile
tasks:
    - init: mkdir -p /workspace/data && mongod --port 3999 --dbpath /workspace/data
    - init: |
        cd services
        yarn
        yarn watch
    - init: |
       cd reader-app
       yarn
       yarn watch

