image:
  file: .gitpod.dockerile
  
tasks:
    - command: mkdir -p /workspace/data && mongod --port 3999 --dbpath /workspace/data
      command: cd services
      command: yarn
      command: yarn watch
    - command: cd reader-app
      command: cd src
      command: yarn watch
      
ports:
  - port: 3001
    onOpen: open-preview
